// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsEbanxIndexImport } from './routes/projects/ebanx/index'
import { Route as ProjectsDesignSystemIndexImport } from './routes/projects/design-system/index'
import { Route as ProjectsCathoIndexImport } from './routes/projects/catho/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsEbanxIndexRoute = ProjectsEbanxIndexImport.update({
  path: '/projects/ebanx/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsDesignSystemIndexRoute = ProjectsDesignSystemIndexImport.update({
  path: '/projects/design-system/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsCathoIndexRoute = ProjectsCathoIndexImport.update({
  path: '/projects/catho/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/catho/': {
      preLoaderRoute: typeof ProjectsCathoIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/design-system/': {
      preLoaderRoute: typeof ProjectsDesignSystemIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/ebanx/': {
      preLoaderRoute: typeof ProjectsEbanxIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProjectsCathoIndexRoute,
  ProjectsDesignSystemIndexRoute,
  ProjectsEbanxIndexRoute,
])
